services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_lms_app
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: app
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lms

  web:
    image: nginx:1.25-alpine
    container_name: mini_lms_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lms

  db:
    image: mysql:8.0
    container_name: mini_lms_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_lms
      MYSQL_USER: lms_user
      MYSQL_PASSWORD: lms_secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hlocalhost", "-ulms_user", "-plms_secret"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - lms

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini_lms_queue
    restart: unless-stopped
    environment:
      CONTAINER_ROLE: queue
    volumes:
      - ./:/var/www/html
      - composer-cache:/root/.composer/cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - lms

  redis:
    image: redis:7-alpine
    container_name: mini_lms_redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lms

volumes:
  db-data:
  redis-data:
  composer-cache:

networks:
  lms:
    driver: bridge
